AWSTemplateFormatVersion: '2010-09-09'
Description: 'Demo Kong Custom Provider CloudFormation '
Parameters:
  AdminURL:
    Type: String
    Description: 'the Kong admin URL, must be reachable from the Lambda '
Resources:
  HeaderService:
    Type: Custom::KongService
    Properties:
      Service:
        name: header-service
        host: httpbin.org
        protocol: https
      AdminURL: !Ref 'AdminURL'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-kong-provider'
  HeaderRoute:
    Type: Custom::KongRoute
    Properties:
      Route:
        paths:
          - /headers
        service: 
          id: !Ref 'HeaderService'
      AdminURL: !Ref 'AdminURL'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-kong-provider'
  KeyAuthPlugin:
    Type: Custom::KongPlugin
    Properties:
      Plugin:
        name: key-auth
        service_id: !Ref 'HeaderService'
      AdminURL: !Ref 'AdminURL'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-kong-provider'
  KongConsumer:
    Type: Custom::KongConsumer
    Properties:
      Consumer:
        username: johndoe
      AdminURL: !Ref 'AdminURL'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-kong-provider'
  KongConsumerACL:
    Type: Custom::KongACL
    DependsOn: KongConsumer
    Properties:
      ACL:
        consumer_id: !Ref 'KongConsumer'
        group: admin
      AdminURL: !Ref 'AdminURL'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-kong-provider'
  KongConsumerApiKey:
    Type: Custom::KongCredential
    DependsOn: KongConsumer
    Properties:
      PluginName: key-auth
      Credential:
        consumer_id: !Ref 'KongConsumer'
        key: 66471684-6BDF-4F11-868F-B513CC391520
      AdminURL: !Ref 'AdminURL'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-kong-provider'
  KongConsumerBasicAuth:
    Type: Custom::KongCredential
    DependsOn: KongConsumer
    Properties:
      PluginName: basic-auth
      Credential:
        consumer_id: !Ref 'KongConsumer'
        username: johndoe
        password: tiger
      AdminURL: !Ref 'AdminURL'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-kong-provider'
